//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Joystick : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 LeftStick
        {
            get
            {
                return SteamVR_Actions.joystick_LeftStick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightStick
        {
            get
            {
                return SteamVR_Actions.joystick_RightStick;
            }
        }
        
        public virtual SteamVR_Action_Pose EssentialPose
        {
            get
            {
                return SteamVR_Actions.joystick_EssentialPose;
            }
        }
    }
}
