//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Vector2 p_joystick_LeftStick;
        
        private static SteamVR_Action_Vector2 p_joystick_RightStick;
        
        private static SteamVR_Action_Pose p_joystick_EssentialPose;
        
        public static SteamVR_Action_Vector2 joystick_LeftStick
        {
            get
            {
                return SteamVR_Actions.p_joystick_LeftStick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 joystick_RightStick
        {
            get
            {
                return SteamVR_Actions.p_joystick_RightStick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Pose joystick_EssentialPose
        {
            get
            {
                return SteamVR_Actions.p_joystick_EssentialPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.joystick_LeftStick,
                    SteamVR_Actions.joystick_RightStick,
                    SteamVR_Actions.joystick_EssentialPose};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.joystick_LeftStick,
                    SteamVR_Actions.joystick_RightStick,
                    SteamVR_Actions.joystick_EssentialPose};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.joystick_EssentialPose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[0];
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.joystick_LeftStick,
                    SteamVR_Actions.joystick_RightStick};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.joystick_LeftStick,
                    SteamVR_Actions.joystick_RightStick};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_joystick_LeftStick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Joystick/in/LeftStick")));
            SteamVR_Actions.p_joystick_RightStick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/Joystick/in/RightStick")));
            SteamVR_Actions.p_joystick_EssentialPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Joystick/in/EssentialPose")));
        }
    }
}
